/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4O.DB4O;
import Business.Doctor.Doctor;
import Business.Donor.Donor;
import Business.Donor.DonorDirectory;
import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Network.Network;

import Business.Organizations.Organizations;
//import Business.Organizations.PatientOrganization;
import Business.Patient.PatientDirectory;
import Business.Patient.patient;
import Business.User.User;
import Business.UserAccount.UserAccount;

//import UserInterface.Patient.Registrationform;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author krishnamayavat
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */

    private Doctor doctor;
    private patient patient;
    private PatientDirectory pDir;
    private DonorDirectory donordirectory;
    private Donor donor;
    private EcoSystem system;
  //  private final Random rand;
  //  private final int otpRange;
    //private EcoSystem ecosystem;
    private DB4O db40=DB4O.getInstance(); 
      public MainFrame() {
        initComponents();
       pDir = new PatientDirectory();
       donordirectory= new DonorDirectory();
        system=db40.retriveSystem();
        Logout.setEnabled(false);
        
        this.setSize(1680, 1050);
  //      rand = new Random();
  //      otpRange = 100000;
        //LoginBtn.setEnabled(false);
        //int otp1 ;
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SplitPane = new javax.swing.JSplitPane();
        RightPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        jUserName = new javax.swing.JLabel();
        UserNameTxtField = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        forgotPwd = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();
        pwdTxtField = new javax.swing.JPasswordField();
        Logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        SplitPane.setDividerSize(2);

        RightPanel.setBackground(new java.awt.Color(255, 153, 153));
        RightPanel.setForeground(new java.awt.Color(255, 255, 255));
        RightPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/covid.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Covid Relief System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(223, 223, 223))
        );

        RightPanel.add(jPanel1, "card3");

        SplitPane.setRightComponent(RightPanel);

        leftPanel.setBackground(new java.awt.Color(255, 153, 153));

        jUserName.setBackground(new java.awt.Color(0, 51, 51));
        jUserName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jUserName.setForeground(new java.awt.Color(255, 255, 255));
        jUserName.setText("User Name ");

        UserNameTxtField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N

        jPassword.setBackground(new java.awt.Color(0, 51, 51));
        jPassword.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.setText("Password  ");

        forgotPwd.setBackground(new java.awt.Color(0, 153, 153));
        forgotPwd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        forgotPwd.setForeground(new java.awt.Color(255, 255, 255));
        forgotPwd.setText("Forgot Password?");
        forgotPwd.setBorder(new javax.swing.border.MatteBorder(null));
        forgotPwd.setBorderPainted(false);
        forgotPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwdActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(0, 153, 153));
        LoginBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Sign IN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 153, 153));
        Logout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Sign Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUserName)
                            .addComponent(jPassword)
                            .addComponent(pwdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(forgotPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(75, 75, 75)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jUserName)
                .addGap(18, 18, 18)
                .addComponent(UserNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(forgotPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(leftPanel);

        getContentPane().add(SplitPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        
        String username =UserNameTxtField.getText();
        char[] passwordCharArray= pwdTxtField.getPassword();
        String password = String.valueOf(passwordCharArray);
        UserAccount ua =system.getUserAccountDirectory().authenticateUser(username, password);
        Enterprise enterprise =null;
        Organizations org =null;
        if(ua==null)
        {
            for(Network network :system.getNetworkList())
            {
                for(Enterprise e:network.getEp().getEnterpriselist())
                {
                    System.out.println("Hey11");
                   ua=e.getUserAccountDirectory().authenticateUser(username, password);
                     System.out.println("Hey11");
                   if(ua==null)
                   {
                       for(Organizations o:e.getOrganizationdir().getOrganizationList())
                       {
                           ua=o.getUserAccountDirectory().authenticateUser(username, password);
                           if(ua!=null)
                           {
                               enterprise=e;
                               org=o;
                               break;
                           }
                       }
                   }
                   else 
                    {
                        enterprise=e;
                        break;
                    }
                if(org!=null)
                break;
                }
                if(enterprise!=null)
                    break;
            
            }
            
            
        }
        if(ua==null)
        {
            JOptionPane.showMessageDialog(null,"Invalid Credentials");
            return;
        }
        else 
        {
            
            Logout.setEnabled(true);
            LoginBtn.setEnabled(false);
            UserNameTxtField.setEnabled(false);
            pwdTxtField.setEnabled(false);
            CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add("workArea", ua.getRole().createWorkArea(RightPanel, ua, org, enterprise, system));
            layout.next(RightPanel);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
            Logout.setEnabled(false);
            LoginBtn.setEnabled(true);
            UserNameTxtField.setEnabled(true);
            pwdTxtField.setEnabled(true);
            
            UserNameTxtField.setText(null);
            pwdTxtField.setText(null);
            
            RightPanel.removeAll();
            JPanel blankJP = new JPanel();
            
           
            
            RightPanel.add("blank",blankJP);
            CardLayout cardLayout=(CardLayout)RightPanel.getLayout();
            cardLayout.next(RightPanel);
            db40.storeSystem(system);
       
    }//GEN-LAST:event_LogoutActionPerformed

    private void forgotPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPwdActionPerformed
        // TODO add your handling code here:
        UserAccount acc =new UserAccount();
        int found =0;
        if(UserNameTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"UserName Field Is empty !");
            return;
        }
        else{
            for(Network network :system.getNetworkList()){
                for(Enterprise e:network.getEp().getEnterpriselist()){
                    for(Organizations o:e.getOrganizationdir().getOrganizationList()){
                        for(UserAccount ua :o.getUserAccountDirectory().getUserAccounts()){
                            if(ua.getUsername().equals(UserNameTxtField.getText())){

                                found =1;
                                acc=ua;

                            }
                        }
                    }
                }
            }
            if(found==1){
                ForgotPwd fpwd= new ForgotPwd(RightPanel,UserNameTxtField.getText(),system);
                CardLayout cardLayout=(CardLayout)RightPanel.getLayout();
                RightPanel.add(fpwd);
                cardLayout.next(RightPanel);
            }
            else
            JOptionPane.showMessageDialog(null,"Invalid UserName !");
    }//GEN-LAST:event_forgotPwdActionPerformed
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JTextField UserNameTxtField;
    private javax.swing.JButton forgotPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jUserName;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPasswordField pwdTxtField;
    // End of variables declaration//GEN-END:variables
}
