/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.DoctorOrganization;
import Business.Organizations.Organizations;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientCostWorkRequest;
import Business.WorkQueue.PatientOrganWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shah's
 */
public class FundRequest extends javax.swing.JPanel {

    /**
     * Creates new form FundRequest
     */
     private JPanel RightPanel;
    private EcoSystem system;
    private UserAccount account;
    private Enterprise enterprise;
    private Enterprise TC;
    private Network lc;
    private Network network;
    public FundRequest(JPanel RightPanel, UserAccount account, Enterprise enterprise,EcoSystem system,Network lc, Enterprise TC) {
        initComponents();
        this.RightPanel = RightPanel;
        this.account = account;
        this.enterprise=enterprise;
        this.system=system;
        this.network=network;
        this.lc=lc;
         btnClaim.setEnabled(false);
        this.TC=TC;
        populateTF();
        
        
    }
    public void populateTF()
    {
        DefaultTableModel model = (DefaultTableModel) jTblFundRequest.getModel();
        model.setRowCount(0);
        for(WorkRequest w:account.getCq().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = w.getMessage();
            row[1] = w.getReceiver();
            row[2] = w.getStatus();
            String result = ((PatientCostWorkRequest) w).getTreatmentCost();
            row[3] = result == null ? "Waiting" : result; 
            if(result==null){
                btnClaim.setEnabled(false);
            }
            else
            btnClaim.setEnabled(true);
       //     row[0] = w.getStatus();
       //     row[1] = w.getMessage();
            model.addRow(row);
        }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTblFundRequest = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        comboRequiredBloodType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnClaim = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        jTblFundRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plasma", "Receiver", "status", "Cost"
            }
        ));
        jScrollPane2.setViewportView(jTblFundRequest);

        btnRequest.setBackground(new java.awt.Color(0, 102, 102));
        btnRequest.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest.setText("REQUEST");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        comboRequiredBloodType.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        comboRequiredBloodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Kidney", "Lungs", "Liver", "Intestine", "Heart", "Pancrease" }));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REQUIRED Blood Type(Plasma) :");

        btnClaim.setBackground(new java.awt.Color(0, 102, 102));
        btnClaim.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnClaim.setForeground(new java.awt.Color(255, 255, 255));
        btnClaim.setText("Fund Claim");
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fund Raise REQUEST");

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRequiredBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel5)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRequiredBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        if(comboRequiredBloodType.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(null,"Please select a blood group !");
            return;
            
        }
        
        else{
        Organizations org =null;
        for(Network network :system.getNetworkList()){
            for(Enterprise e:network.getEp().getEnterpriselist()){
                for(Organizations o:e.getOrganizationdir().getOrganizationList()){
                    if(network.equals(lc)){
                        if(e.equals(TC)){
                            if(o instanceof DoctorOrganization)
                                org=o;
                            break;
                        }
                    }
                }
            }
        }
        if(org !=null){
            
            String message = (String)comboRequiredBloodType.getSelectedItem();
            PatientCostWorkRequest request= new PatientCostWorkRequest();
            request.setMessage(message);
            request.setSender(account);
       //     request.setMessage("whats the cost ?");
            request.setStatus("Sent");
            org.getCostEstimation().getWorkRequestList().add(request);
            account.getCq().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null,"fund estimation sent !");
            populateTF();
            try{
            Email emailConfig= new Email();
            Properties smtpProperties = emailConfig.loadProperties();
            String email = account.getUsername();
            emailConfig.sendEmail(smtpProperties, email, "Request Initiated", "Your request has being sent to the Hospital");
        }
            catch(Exception ex){
                
            }
    }//GEN-LAST:event_btnRequestActionPerformed
        if(org ==null)
        {
            JOptionPane.showMessageDialog(null,"There was no Doctors Organization in the Hospital you have Selected !");
            return;
        }
        }
    
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        // TODO add your handling code here:
        /*if(Cost.getSelectedRow()>0){
            String status =(String)Cost.getValueAt(Cost.getSelectedRow(),3);
            if(!status.equals("Waiting")){
                MoneyClaim.setEnabled(true);
            }
        }*/
        int selectedRow=jTblFundRequest.getSelectedRow();
        if(selectedRow>=0){
        NGO i =new NGO(RightPanel, account,enterprise,network,system,lc,TC,(String)jTblFundRequest.getValueAt(jTblFundRequest.getSelectedRow(),3));
                CardLayout layout=(CardLayout)RightPanel.getLayout();
                RightPanel.add(i);
                layout.next(RightPanel);
        }
        else
            JOptionPane.showMessageDialog(null,"Select a row !");
        
            
        
        
        
    }//GEN-LAST:event_btnClaimActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClaim;
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox<String> comboRequiredBloodType;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblFundRequest;
    // End of variables declaration//GEN-END:variables
}
