/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organizations.NGOVolunteer;
import Business.Organizations.Organizations;
import static Business.Organizations.Organizations.Type.NGOVolunteer;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRequestsInsuranceCompany;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shah's
 */
public class NGO extends javax.swing.JPanel {

    /**
     * Creates new form NGO
     */
    private JPanel RightPanel;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem system;
     private Enterprise TC;
    private Network lc;
    private String cost ;
    public NGO(JPanel RightPanel,UserAccount account,Enterprise enterprise,Network network,EcoSystem system,Network lc, Enterprise TC,String cost ) {
        initComponents();
        this.RightPanel=RightPanel;
        this.account= account;
        this.enterprise=enterprise;
        this.network=network;
        this.system=system;
        this.lc=lc;
        this.TC=TC;
        this.cost=cost;
        populateInsuranceCompanyTable();
        populateICBox(); 
    }
    public void populateICBox()
    {
        jComboNGOCompany.removeAllItems();
        for(Enterprise e: lc.getEp().getEnterpriselist()){
            if(e instanceof NGOEnterprise){
                jComboNGOCompany.addItem(e);}
        }
    }
    public void populateInsuranceCompanyTable()
    {
     DefaultTableModel model = (DefaultTableModel) jTblNGOs.getModel();
        model.setRowCount(0);
        for(WorkRequest w:account.getClaimMoney().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0] = w.getReceiver();
            row[1] = w.getMessage();
            row[2]=w.getStatus();
            model.addRow(row);
    }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTblNGOs = new javax.swing.JTable();
        btnFundClaim = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jComboNGOCompany = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        jTblNGOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receiver", "message", "status"
            }
        ));
        jScrollPane3.setViewportView(jTblNGOs);

        btnFundClaim.setBackground(new java.awt.Color(0, 153, 153));
        btnFundClaim.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnFundClaim.setText("Fund Claim");
        btnFundClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundClaimActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jComboNGOCompany.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" SELECT NGO :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboNGOCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFundClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboNGOCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFundClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFundClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundClaimActionPerformed
        // TODO add your handling code here:
        Organizations org =null;
        for(Network network :system.getNetworkList()){
            for(Enterprise e:network.getEp().getEnterpriselist()){
                for(Organizations o:e.getOrganizationdir().getOrganizationList()){
                    if(network.equals(lc)){
                        if(e.equals(jComboNGOCompany.getSelectedItem())){
                            if(o instanceof NGOVolunteer)
                            org=o;
                            break;
                        }
                    }
                }
            }
        }
        if(org !=null){
            PatientRequestsInsuranceCompany request = new PatientRequestsInsuranceCompany();
            request.setSender(account);
            request.setMessage(String.valueOf(cost));
            request.setStatus("Sent");
            org.getClaimMoney().getWorkRequestList().add(request);
            account.getClaimMoney().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null,"fund claim sent to NGO !");
            try{
            Email emailConfig= new Email();
            Properties smtpProperties = emailConfig.loadProperties();
            String email = account.getUsername();
            emailConfig.sendEmail(smtpProperties, email, "Request Initiated", "Your request has being sent to the NGO!");
        }
            catch(Exception ex){
                
            }
            populateInsuranceCompanyTable();
         
    }//GEN-LAST:event_btnFundClaimActionPerformed
    if(org==null){
       JOptionPane.showMessageDialog(null,"No NGO Volunteer Organization created !");
    }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFundClaim;
    private javax.swing.JComboBox<Enterprise> jComboNGOCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblNGOs;
    // End of variables declaration//GEN-END:variables
}
