/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Network.*;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organizations.Organizations;
import Business.Organizations.PatientOrganization;
//import Business.Organizations.PatientOrganization;
import Business.Enterprise.UserEnterprise;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Shah's
 */
//Trying again
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel RightPanel;
    private UserAccount account;
    private Enterprise enterprise;
    private PatientDirectory pDir;
    private EcoSystem System;
   // private Organizations organization;
    private PatientOrganization organization;

    public PatientWorkAreaJPanel(JPanel RightPanel, UserAccount account, PatientOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.RightPanel=RightPanel;
        this.account = account;
        this.organization = organization;
        this.System=business;
        this.enterprise = enterprise;
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestPlasma = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnAccountManager = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        btnRequestPlasma.setBackground(new java.awt.Color(0, 102, 102));
        btnRequestPlasma.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnRequestPlasma.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestPlasma.setText("REQUEST FOR PLASMA");
        btnRequestPlasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestPlasmaActionPerformed(evt);
            }
        });

        btnViewDetails.setBackground(new java.awt.Color(0, 102, 102));
        btnViewDetails.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("VIEW DETAILS");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnAccountManager.setBackground(new java.awt.Color(0, 102, 102));
        btnAccountManager.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnAccountManager.setForeground(new java.awt.Color(255, 255, 255));
        btnAccountManager.setText("ACCOUNT MANAGER");
        btnAccountManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManagerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAccountManager, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRequestPlasma, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addComponent(btnRequestPlasma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccountManager, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestPlasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestPlasmaActionPerformed

      CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add("OrganRequest", new PlasmaRequest(RightPanel, account,enterprise, System));
      layout.next(RightPanel);
    }//GEN-LAST:event_btnRequestPlasmaActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add("ViewDetails", new ViewDetails(RightPanel, account,enterprise, System));
      layout.next(RightPanel);
       
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnAccountManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManagerActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add( "PatientAccountManager",new PatientUpdateProfileJPanel(RightPanel, account, enterprise));
      layout.next(RightPanel);
    }//GEN-LAST:event_btnAccountManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountManager;
    private javax.swing.JButton btnRequestPlasma;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
