/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Donor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organizations.DonorOrganization;
import Business.Organizations.PatientOrganization;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;

//import UserInterface.Patient.PlasmaRequest;

import UserInterface.Patient.PlasmaRequest;
import UserInterface.Patient.ViewDetails;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author krishnamayavat
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorWorkAreaJPanel
     */
    
    private JPanel RightPanel;
    private UserAccount account;
    private Enterprise enterprise;
    //private PatientDirectory pDir;
    private EcoSystem System;
    private DonorOrganization organization;
    public DonorWorkAreaJPanel(JPanel RightPanel, UserAccount account, DonorOrganization organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.RightPanel=RightPanel;
        this.account = account;
        this.organization = organization;
        this.System=business;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDonateRequest = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(null);

        btnDonateRequest.setBackground(new java.awt.Color(0, 153, 153));
        btnDonateRequest.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnDonateRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnDonateRequest.setText("Donation Request");
        btnDonateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateRequestActionPerformed(evt);
            }
        });
        add(btnDonateRequest);
        btnDonateRequest.setBounds(170, 40, 315, 50);

        btnViewDetails.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDetails.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails);
        btnViewDetails.setBounds(170, 110, 315, 49);

        btnUpdateProfile.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdateProfile.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnUpdateProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });
        add(btnUpdateProfile);
        btnUpdateProfile.setBounds(170, 180, 315, 49);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateRequestActionPerformed
        // TODO add your handling code here:
        
        /*for(Network network: System.getNetworkList())
         {
             for(Enterprise enterprise: network.getEp().getEnterpriselist())
             {
                 if(enterprise instanceof HospitalEnterprise)
                 {   
                     this.enterprise=enterprise;
                     break;                  
                 }
             }
             
         }*/
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        RightPanel.add("PlasmaDonate", new PlasmaDonateJPanel(RightPanel, account, enterprise, System));
        layout.next(RightPanel);
        
    }//GEN-LAST:event_btnDonateRequestActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        RightPanel.add("DonorProfile", new DonorUpdateProfileJPanel(RightPanel, account, enterprise));
        layout.next(RightPanel);
        
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add("ViewStatus", new ViewStatus(RightPanel, account,enterprise, System));
      layout.next(RightPanel);
    }//GEN-LAST:event_btnViewDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonateRequest;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewDetails;
    // End of variables declaration//GEN-END:variables
}
