/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author heer
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkAreaJPanel
     */
    private JPanel RightPanel;
    private Enterprise enterprise;
    //EcoSystem Business;
    public HospitalAdminWorkAreaJPanel(JPanel RightPanel, Enterprise enterprise) {
        initComponents();
        this.RightPanel=RightPanel;
        this.enterprise=enterprise;
        
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddDoc = new javax.swing.JButton();
        btnManageOrg = new javax.swing.JButton();
        btnManageDoc = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hospital Admin Dashboard");

        btnAddDoc.setBackground(new java.awt.Color(0, 153, 204));
        btnAddDoc.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnAddDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDoc.setText("ADD A DOCTOR");
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });

        btnManageOrg.setBackground(new java.awt.Color(0, 153, 204));
        btnManageOrg.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnManageOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrg.setText("MANAGE ORGANIZATION");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });

        btnManageDoc.setBackground(new java.awt.Color(0, 153, 204));
        btnManageDoc.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnManageDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDoc.setText("MANAGE DOCTOR");
        btnManageDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAddDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        // TODO add your handling code here:
        AddDoctorJPanel ad= new AddDoctorJPanel(RightPanel,enterprise.getOrganizationdir());
        CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(ad);
            layout.next(RightPanel);
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:
        ManageOrganization mo=new ManageOrganization(RightPanel,enterprise.getOrganizationdir());
        CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(mo);
            layout.next(RightPanel);
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnManageDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDocActionPerformed
        // TODO add your handling code here:
        ManageDoctorJPanel md=new ManageDoctorJPanel(RightPanel,enterprise);
        CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(md);
            layout.next(RightPanel);
    }//GEN-LAST:event_btnManageDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDoc;
    private javax.swing.JButton btnManageDoc;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
